"""Measure the commercial ``ubc`` Rust engine on the same bench graphs.

Activated by ``bench/benchmark.py`` automatically when the binary is found
(``UBC`` env var, ``ubc`` on PATH, or ``.tools/ubc``); skipped with a notice
otherwise.

How the graph reaches ubc: the synthetic ``bench/graphs/graph_N.json`` is fed
through ubCode's ``needs.external_needs`` / ``json_path`` project config — no
Sphinx build involved. ubc's free open-source license is granted per project
path (it checks that the containing git repo has a publicly reachable remote),
so the bench project directory lives inside the ``.tools/sphinx-needs-demo``
clone of useblocks' public demo repo. Set ``UBC_PROJECT`` to override.

Two measured lanes, both honest about what they include:

* ``ubc_cli`` — END-TO-END wall clock of ``ubc query cypher … -f json``:
  process start + license check + on-disk index cache load + query + full JSON
  result serialization. This is what a CI or shell user pays per query.
* ``ubc_mcp`` — WARM per-query latency against a persistent ``ubc serve mcp``
  process (index already resident): stdio JSON-RPC round-trip included; note
  that the MCP server caps the serialized result at 200 rows (totalRows is
  still exact), so very large result sets serialize less than the CLI lane.

``load_ms`` for this variant is the first CLI run after the graph is swapped
in: process start + full index build + query. A separate single ``--no-cache``
run (index rebuilt, no cache reads) is reported as ``no_cache_ms``.

Row counts are the number of DISTINCT ids parsed from the CLI JSON output and
feed the benchmark's counts-agree cross-check against every other engine.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
from statistics import median

ROOT = Path(__file__).resolve().parent.parent

MAX_REPEAT_MS = 3000.0  # same discipline as _run_variant.py

# Identical workloads to _run_variant.CYPHER, projected to `.id` so the wire
# format (a list of ids) matches what select_ids() returns for the other lanes.
CYPHER_IDS = {
    "A_flat": "MATCH (r:swreq) WHERE r.status = 'open' RETURN r.id",
    "B_antijoin": "MATCH (r:swreq) WHERE NOT ( (r)<-[:links]-(:test) ) RETURN r.id",
    "C_join": (
        "MATCH (sr:sysreq)-[:implements]->(f:fsr)-[:derives_from]->(s:safety_goal) "
        "WHERE s.asil = 'D' RETURN sr.id"
    ),
    "D_closure": "MATCH (h:safety_goal)<-[*1..]-(n) WHERE h.id = 'SG_0' RETURN n.id",
    "E_complex": "MATCH (sr:swreq)-[:links]->(r:req) WHERE sr.status = 'open' AND r.status = 'open' AND NOT ( (sr)<-[:implements]-(:impl) ) RETURN sr.id",
}

UBPROJECT_TOML = """\
"$schema" = "https://ubcode.useblocks.com/ubproject.schema.json"
# Generated by bench/ubc_variant.py — a needs-only project that loads the
# synthetic benchmark graph via external_needs, mirroring bench/generate.py.

[[needs.types]]
directive = "safety_goal"
title = "Safety Goal"
prefix = "SG"

[[needs.types]]
directive = "fsr"
title = "FSR"
prefix = "FSR"

[[needs.types]]
directive = "sysreq"
title = "SysReq"
prefix = "SYSREQ"

[[needs.types]]
directive = "req"
title = "Req"
prefix = "REQ"

[[needs.types]]
directive = "swreq"
title = "SwReq"
prefix = "SWREQ"

[[needs.types]]
directive = "impl"
title = "Impl"
prefix = "IMPL"

[[needs.types]]
directive = "test"
title = "Test"
prefix = "TEST"

[needs.links.links]
outgoing = "links"
incoming = "linked by"

[needs.links.implements]
outgoing = "implements"
incoming = "implemented by"

[needs.links.derives_from]
outgoing = "derives from"
incoming = "derived to"

[needs.fields.status]
description = "status"
type = "string"
default = ""

[needs.fields.asil]
description = "asil"
type = "string"
default = ""

[[needs.external_needs]]
json_path = "graph.json"
"""


def find_ubc() -> str | None:
    for cand in (os.environ.get("UBC"), shutil.which("ubc"), str(ROOT / ".tools" / "ubc")):
        if cand and Path(cand).is_file() and os.access(cand, os.X_OK):
            return cand
    return None


def default_project() -> Path:
    return ROOT / ".tools" / "sphinx-needs-demo" / "benchproj"


def prepare_project(project: Path, graph: Path) -> None:
    if not project.parent.exists():
        raise SystemExit(
            f"ubc bench project host missing: {project.parent}\n"
            "ubc's free OSS license is granted per publicly-reachable git repo; "
            "clone useblocks' public demo next to the binary:\n"
            f"  git clone --depth 1 https://github.com/useblocks/sphinx-needs-demo "
            f"{ROOT / '.tools' / 'sphinx-needs-demo'}"
        )
    project.mkdir(exist_ok=True)
    (project / "ubproject.toml").write_text(UBPROJECT_TOML, encoding="utf-8")
    shutil.copyfile(graph, project / "graph.json")
    shutil.rmtree(project / ".ub_cache", ignore_errors=True)


def cli_cmd(ubc: str, cypher: str, extra: list[str] | None = None) -> list[str]:
    return [ubc, "query", "cypher", cypher, "-f", "json", "-q", *(extra or [])]


def run_cli(ubc: str, project: Path, cypher: str, extra: list[str] | None = None) -> tuple[float, list]:
    t0 = time.perf_counter()
    proc = subprocess.run(
        cli_cmd(ubc, cypher, extra), cwd=project, capture_output=True, text=True, timeout=300
    )
    dt = (time.perf_counter() - t0) * 1000.0
    if proc.returncode != 0:
        raise RuntimeError(f"ubc failed ({proc.returncode}): {proc.stderr.strip()[:500]}")
    return dt, json.loads(proc.stdout or "[]")


def distinct_ids(rows: list) -> int:
    return len({next(iter(r.values()), None) for r in rows if isinstance(r, dict)})


class McpClient:
    """Minimal JSON-RPC-over-stdio client for ``ubc serve mcp``. stderr goes to
    /dev/null — the server logs there and a full pipe would deadlock it."""

    def __init__(self, ubc: str, project: Path) -> None:
        self.proc = subprocess.Popen(
            [ubc, "serve", "mcp"],
            cwd=project,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
        )
        self._id = 0
        self._send({"jsonrpc": "2.0", "id": self._next(), "method": "initialize",
                    "params": {"protocolVersion": "2024-11-05", "capabilities": {},
                               "clientInfo": {"name": "needquery-bench", "version": "0"}}})
        self._recv()
        self._send({"jsonrpc": "2.0", "method": "notifications/initialized"})

    def _next(self) -> int:
        self._id += 1
        return self._id

    def _send(self, obj: dict) -> None:
        assert self.proc.stdin is not None
        self.proc.stdin.write(json.dumps(obj) + "\n")
        self.proc.stdin.flush()

    def _recv(self) -> dict:
        assert self.proc.stdout is not None
        while True:
            line = self.proc.stdout.readline()
            if not line:
                raise RuntimeError("ubc mcp server exited")
            line = line.strip()
            if line:
                return json.loads(line)

    def query(self, cypher: str) -> dict:
        self._send({"jsonrpc": "2.0", "id": self._next(), "method": "tools/call",
                    "params": {"name": "query_cypher",
                               "arguments": {"query": cypher, "file_path": "graph.json"}}})
        resp = self._recv()
        if "result" not in resp or resp["result"].get("isError"):
            raise RuntimeError(f"mcp query failed: {json.dumps(resp)[:300]}")
        return resp["result"].get("structuredContent", {})

    def close(self) -> None:
        self.proc.terminate()
        self.proc.wait(timeout=10)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--graph", required=True)
    ap.add_argument("--repeat", type=int, default=5)
    ap.add_argument("--project", default=None)
    args = ap.parse_args()

    ubc = find_ubc()
    if not ubc:
        raise SystemExit("ubc binary not found (UBC env, PATH, or .tools/ubc)")
    project = Path(args.project) if args.project else default_project()
    prepare_project(project, Path(args.graph))

    # First run: process start + full index build + query. Reported as load_ms.
    load_ms, _ = run_cli(ubc, project, CYPHER_IDS["A_flat"])
    # One --no-cache run: index rebuilt without on-disk cache reads.
    no_cache_ms, _ = run_cli(ubc, project, CYPHER_IDS["A_flat"], ["--no-cache"])

    wl: dict = {}
    mcp = McpClient(ubc, project)
    try:
        for key, cypher in CYPHER_IDS.items():
            # CLI lane: end-to-end wall clock, warm on-disk cache, best of N.
            cli_runs: list[float] = []
            rows: list = []
            for _ in range(args.repeat):
                dt, rows = run_cli(ubc, project, cypher)
                cli_runs.append(dt)
                if cli_runs[0] > MAX_REPEAT_MS:
                    break
            count = distinct_ids(rows)

            # MCP lane: warm server, first call discarded (server-side warm-up).
            mcp.query(cypher)
            mcp_runs: list[float] = []
            total_rows = None
            truncated = False
            for _ in range(args.repeat):
                t0 = time.perf_counter()
                sc = mcp.query(cypher)
                mcp_runs.append((time.perf_counter() - t0) * 1000.0)
                total_rows = sc.get("totalRows")
                truncated = bool(sc.get("truncated"))
                if mcp_runs[0] > MAX_REPEAT_MS:
                    break
            if total_rows is not None and total_rows != len(rows):
                # totalRows counts result rows pre-truncation; the CLI JSON is
                # the authoritative full result. They must agree.
                raise SystemExit(
                    f"ubc CLI/MCP row disagreement on {key}: cli={len(rows)} mcp={total_rows}"
                )

            def stats(runs: list[float]) -> dict:
                return {
                    "runs": [round(r, 3) for r in runs],
                    "best": round(min(runs), 3),
                    "median": round(median(runs), 3),
                    "count": count,
                }

            mcp_stats = stats(mcp_runs)
            mcp_stats["result_truncated_to_200_rows"] = truncated
            wl[key] = {"impls": {"ubc_cli": stats(cli_runs), "ubc_mcp": mcp_stats}}
    finally:
        mcp.close()

    json.dump(
        {
            "variant": "ubc",
            "compiled": True,
            "binary_version": subprocess.run(
                [ubc, "--version"], capture_output=True, text=True
            ).stdout.strip(),
            "load_ms": round(load_ms, 3),
            "no_cache_ms": round(no_cache_ms, 3),
            "workloads": wl,
        },
        sys.stdout,
    )


if __name__ == "__main__":
    main()
